spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autho
    username: postgres
    password: password

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  cors:
    allowedOrigins: http://localhost:5000

  jwt:
    secret_key: my_jwt_secret_key

server:
  error:
    include-message: always
